function res = mtimes(a,u)

[~,Nx,Np,Nc] = size(u);
    
if a.adjoint
    res =   cat(1,u(1:end-2,:,:,:),zeros(1,Nx,Np,Nc),zeros(1,Nx,Np,Nc))...
         -2*cat(1,zeros(1,Nx,Np,Nc),u(1:end-2,:,:,:),zeros(1,Nx,Np,Nc))...
           +cat(1,zeros(1,Nx,Np,Nc),zeros(1,Nx,Np,Nc),u(1:end-2,:,:,:));
else
    res =   u... 
         -2*cat(1,u(2:end,:,:,:),u(end,:,:,:))...
           +cat(1,u(3:end,:,:,:),u(end,:,:,:),u(end,:,:,:));
end